### ISSUE TITLE
GPP partitioned files 

### ISSUE THREAD

**Issue by davidjpmoore** [davidjpmoore/Calloc_AmerifluxProcessing#1]
@fmontane5 and @malloryb 
If you have the GPP and TER files for Niwot Ridge completed could you post them to iplant when you get a chance?
It would be great to have them posted to here:
/iplant/home/davidjpmoore/CarbonAllocation/PartitionedFluxData/NiwotRidge

**Comment by fmontane5** [comment]
@davidjpmoore and @malloryb 

I tried the partition for Niwot, but there are problems to detect Ustar thresholds with bootstrap in some years (the Ustar filter in REddyProc is still a beta version). The error may be either related with REddyProc package or maybe because of too few records available for threshold detection in that year (because for some years it works). The problem is only for Ustar threshold detection with bootstrap for some years. No problems with partition. For instance in Niwot, I got the following Ustar thresholds detected with bootstrap for different years (the order below is Ustar original series, Ustar5%boostrap, UstarMedianbootstrap and Ustar95%bootstrap):

Year 1999: Error 
Year 2000: 0.7525   0.397 0.53915   0.79075 
Year 2001: 0.46825  0.38861 0.56528 0.8518
Year 2002: Error
Year 2003: 0.42627  0.27909 0.41145 0.74418
Year 2004: Error (this is the year with strange behaviour when partitioning)
Year 2005: Error
Year 2006: 0.78417  0.38019 0.47964 0.77109 (here I do not understand why the Ustar in the original series seems to be out of the 90% confidence interval)
Year 2007: 0.62862  0.29155 0.40644 0.65627
Year 2008: 0.46219  0.28003 0.37627 0.55948
Year 2009: 0.376    0.25601 0.34357 0.60687
Year 2010: 0.36271  0.32669 0.39903 0.76605
Year 2011: 0.37306  0.26268 0.37616 0.87468
Year 2012: 0.45842  0.27391 0.37364 0.66606
Year 2013: 0.41741  0.29214 0.44619 0.76838

What do you suggest to do with the years where Ustar thresholds could not be detected?
Maybe use some "average" Ustar threshold from the ones available?
I have not tried yet, but I guess that if we define Ustar thresholds for years with errors, we could still do the partition.

**Comment by davidjpmoore** [comment]
Can you build an 'average' or median ustar and confidence interval based on the other years and apply it to the years that do not converge?

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by davidjpmoore** [comment]
I think that we should use the values @fmontane5 has calculated to estimate the best guess for the years where the bootstrapping method failed to converge. 

For 2002, 2004 & 2007 we could use 
0.29155 (5%)    0.40644 (median)    0.755115 (95%)

These values are the simple median of the other years lower, median and upper estimates.

@fmontane5 @malloryb Looking at the values - it seems that 2000 and 2001 have pretty high values .... I wonder whether those two years had lower fluxes or lower windspeeds on average? Of course the 95% CI's overlap pretty much completely so perhaps it's not worth pursuing in great depth.

![image](https://cloud.githubusercontent.com/assets/6138344/8509299/062d2eb2-2251-11e5-8c90-8d16093e4c96.png)

**Comment by malloryb** [comment]
I looked at average daily wind speed and average daily flux for Niwot Ridge
in 2000 and 2001 and compared them to "normal" years (2005 & 2006). Nothing
is jumping out at me, except a big spike in CO2 flux in 2001.

[image: Inline image 1][image: Inline image 2]

**Comment by davidjpmoore** [comment]
Ok - is there any reason not to go ahead with the following:
Ustar filter for 2002, 2004 & 2007 
0.29155 (5%) 0.40644 (median) 0.755115 (95%)

This looks like like it's good?

**Comment by malloryb** [comment]
I don't see any reason why not. I'm moving ahead with those values.

**Comment by davidjpmoore** [comment]
Ok ... closing this issue
